Catalyst Build Executor: src/cbe.cpp File Reference
cbe.cpp File Reference
#include "cbe/builder.hpp"
#include "cbe/executor.hpp"
#include "cbe/parser.hpp"
#include <charconv>
#include <cstring>
#include <filesystem>
#include <format>
#include <iostream>
#include <print>
#include <string>
Classes
struct CliArgs
Functions
void printHelp ()
void printVersion ()
catalyst::Result< CliArgs > cliArgs (int argc, const char *const *argv)
int main (const int argc, const char *const *argv)
Function Documentation
cliArgs()
catalyst::Result< CliArgs > cliArgs (int argc, const char *const * argv)
Definition at line 95 of file cbe.cpp.
References catalyst::ExecutorConfig::build_file, catalyst::ExecutorConfig::clean, CliArgs::compdb, CliArgs::config, catalyst::ExecutorConfig::dry_run, catalyst::ExecutorConfig::estimates_file, CliArgs::estimates_file, CliArgs::graph, CliArgs::input_path, catalyst::ExecutorConfig::jobs, printHelp(), and printVersion().
Referenced by main().
main()
int main (const int argc, const char *const * argv)
Definition at line 43 of file cbe.cpp.
References cliArgs(), catalyst::Executor::emit_compdb(), and catalyst::parse().
printHelp()
void printHelp ()
Definition at line 13 of file cbe.cpp.
Referenced by cliArgs().
printVersion()
void printVersion ()
Definition at line 28 of file cbe.cpp.
Referenced by cliArgs().