Catalyst Build Executor: catalyst::CBEBuilder Class Reference
catalyst::CBEBuilder Class Reference
Builder class for constructing the build graph.
#include <builder.hpp>
Public Member Functions
Result< void > add_step (BuildStep &&bs)
Adds a build step to the underlying graph.
const BuildGraph & graph () const
BuildGraph && emit_graph ()
Returns the built graph by moving it out of the builder.
void add_definition (std::string_view key, std::string_view value)
Adds a global definition/variable.
void add_resource (std::shared_ptr< void > res)
Registers a resource to be managed by the graph's lifetime.
const Definitions & definitions () const
Private Attributes
BuildGraph graph_
Definitions definitions_
Friends
Result< void > parse (CBEBuilder &, const std::filesystem::path &)
Parses a build manifest file.
Result< void > parse_bin (CBEBuilder &)
Parses the binary cache format (.catalyst.bin).
Result< void > emit_bin (CBEBuilder &)
Serializes the current build graph to the binary cache format.
Detailed Description
Builder class for constructing the build graph.
This class acts as a facade for populating the BuildGraph and Definitions. It is used by parsers to construct the build representation.
Definition at line 16 of file builder.hpp.
Member Function Documentation
add_definition()
void catalyst::CBEBuilder::add_definition (std::string_view key, std::string_view value) inline
Adds a global definition/variable.
Parameters
key The name of the definition.
value The value of the definition.
Definition at line 42 of file builder.hpp.
References definitions_.
Referenced by catalyst::for(), and catalyst::anonymous_namespace{parser.cpp}::parse_def().
add_resource()
void catalyst::CBEBuilder::add_resource (std::shared_ptr< void > res) inline
Registers a resource to be managed by the graph's lifetime.
Parameters
res A shared pointer to the resource.
Definition at line 50 of file builder.hpp.
References catalyst::BuildGraph::add_resource(), and graph_.
add_step()
Result< void > catalyst::CBEBuilder::add_step (BuildStep && bs)
Adds a build step to the underlying graph.
Parameters
bs The build step to add.
Returns
Success or error.
Definition at line 5 of file builder.cpp.
References catalyst::BuildGraph::add_step(), and graph_.
Referenced by catalyst::anonymous_namespace{parser.cpp}::parse_step().
definitions()
const Definitions & catalyst::CBEBuilder::definitions () const inline
Definition at line 54 of file builder.hpp.
References definitions_.
Referenced by catalyst::Executor::emit_compdb(), and catalyst::Executor::execute().
emit_graph()
BuildGraph && catalyst::CBEBuilder::emit_graph () inline
Returns the built graph by moving it out of the builder.
Returns
The completed BuildGraph.
Definition at line 33 of file builder.hpp.
References graph_.
Referenced by catalyst::Executor::clean(), catalyst::Executor::emit_compdb(), catalyst::Executor::emit_graph(), and catalyst::Executor::execute().
graph()
const BuildGraph & catalyst::CBEBuilder::graph () const inline
Definition at line 25 of file builder.hpp.
References graph_.
Friends And Related Symbol Documentation
emit_bin
Result< void > emit_bin (CBEBuilder &) friend
Serializes the current build graph to the binary cache format.
Parameters
builder The builder containing the graph to serialize.
Returns
Success or error.
parse
Result< void > parse (CBEBuilder & builder, const std::filesystem::path & path) friend
Parses a build manifest file.
Detects if a binary cache exists and is up-to-date; if so, loads that. Otherwise, parses the text-based manifest format.
Parameters
builder The builder to populate with parsed steps and definitions.
path The path to the manifest file (typically "catalyst.build").
Returns
Success or error.
Definition at line 56 of file parser.cpp.
parse_bin
Result< void > parse_bin (CBEBuilder & builder) friend
Parses the binary cache format (.catalyst.bin).
This is a fast-path loading mechanism that bypasses text parsing.
Parameters
builder The builder to populate.
Returns
Success or error.
Definition at line 62 of file binary.cpp.
Member Data Documentation
definitions_
Definitions catalyst::CBEBuilder::definitions_ private
Definition at line 64 of file builder.hpp.
Referenced by add_definition(), and definitions().
graph_
BuildGraph catalyst::CBEBuilder::graph_ private
Definition at line 63 of file builder.hpp.
Referenced by add_resource(), add_step(), emit_graph(), graph(), and catalyst::reserve().
The documentation for this class was generated from the following files:
include/cbe/builder.hpp
src/builder.cpp