Catalyst Build Executor: catalyst::BuildGraph Class Reference
catalyst::BuildGraph Class Reference
Represents the dependency graph of the build system.
#include <graph.hpp>
Classes
struct Node
Represents a node in the dependency graph (typically a file).
Public Member Functions
size_t get_or_create_node (std::string_view path)
Retrieves the index of an existing node or creates a new one.
Result< size_t > add_step (BuildStep step)
Adds a new build step to the graph.
void add_resource (std::shared_ptr< void > res)
Keeps a resource alive for the lifetime of the graph.
const std::vector< Node > & nodes () const
const std::vector< BuildStep > & steps () const
Result< std::vector< size_t > > topo_sort () const
Performs a topological sort of the graph.
Private Attributes
std::vector< Node > nodes_
std::vector< BuildStep > steps_
std::unordered_map< std::string_view, size_t > index_
std::vector< std::shared_ptr< void > > resources_
Friends
Result< void > parse (class CBEBuilder &, const std::filesystem::path &)
Parses a build manifest file.
Result< void > parse_bin (class CBEBuilder &)
Parses the binary cache format (.catalyst.bin).
Result< void > emit_bin (class CBEBuilder &)
Serializes the current build graph to the binary cache format.
Detailed Description
Represents the dependency graph of the build system.
This class manages nodes (files) and edges (dependencies), as well as the list of build steps. It also manages the lifetime of resources (like memory-mapped files) used by the graph strings.
Definition at line 22 of file graph.hpp.
Member Function Documentation
add_resource()
void catalyst::BuildGraph::add_resource (std::shared_ptr< void > res) inline
Keeps a resource alive for the lifetime of the graph.
Parameters
res A shared pointer to the resource (e.g., MappedFile).
Definition at line 53 of file graph.hpp.
References resources_.
Referenced by catalyst::CBEBuilder::add_resource(), and catalyst::parse_depfile().
add_step()
Result< size_t > catalyst::BuildGraph::add_step (BuildStep step)
Adds a new build step to the graph.
This method parses the step's inputs, creates necessary nodes and edges, and handles dependency file parsing if applicable.
Parameters
step The build step to add.
Returns
The index of the added step, or an error if a producer for the output already exists.
Definition at line 123 of file graph.cpp.
References get_or_create_node(), catalyst::BuildStep::inputs, nodes_, catalyst::BuildStep::opaque_inputs, catalyst::BuildStep::output, catalyst::parse_depfile(), catalyst::BuildStep::parsed_inputs, steps_, and catalyst::BuildStep::tool.
Referenced by catalyst::CBEBuilder::add_step().
get_or_create_node()
size_t catalyst::BuildGraph::get_or_create_node (std::string_view path)
Retrieves the index of an existing node or creates a new one.
Parameters
path The file path associated with the node.
Returns
The index of the node in the nodes_ vector.
Definition at line 19 of file graph.cpp.
References index_, and nodes_.
Referenced by add_step().
nodes()
const std::vector< Node > & catalyst::BuildGraph::nodes () const inline
Definition at line 57 of file graph.hpp.
References nodes_.
Referenced by catalyst::Executor::emit_compdb(), catalyst::Executor::emit_graph(), and catalyst::Executor::execute().
steps()
const std::vector< BuildStep > & catalyst::BuildGraph::steps () const inline
Definition at line 60 of file graph.hpp.
References steps_.
Referenced by catalyst::Executor::clean(), catalyst::Executor::emit_compdb(), catalyst::Executor::emit_graph(), and catalyst::Executor::execute().
topo_sort()
Result< std::vector< size_t > > catalyst::BuildGraph::topo_sort () const
Performs a topological sort of the graph.
Returns
A vector of node indices in topological order (dependencies first), or an error if a cycle is detected.
Definition at line 191 of file graph.cpp.
References nodes_.
Referenced by catalyst::Executor::emit_compdb().
Friends And Related Symbol Documentation
emit_bin
Result< void > emit_bin (class CBEBuilder &) friend
Serializes the current build graph to the binary cache format.
Parameters
builder The builder containing the graph to serialize.
Returns
Success or error.
parse
Result< void > parse (class CBEBuilder & builder, const std::filesystem::path & path) friend
Parses a build manifest file.
Detects if a binary cache exists and is up-to-date; if so, loads that. Otherwise, parses the text-based manifest format.
Parameters
builder The builder to populate with parsed steps and definitions.
path The path to the manifest file (typically "catalyst.build").
Returns
Success or error.
Definition at line 56 of file parser.cpp.
parse_bin
Result< void > parse_bin (class CBEBuilder & builder) friend
Parses the binary cache format (.catalyst.bin).
This is a fast-path loading mechanism that bypasses text parsing.
Parameters
builder The builder to populate.
Returns
Success or error.
Definition at line 62 of file binary.cpp.
Member Data Documentation
index_
std::unordered_map<std::string_view, size_t> catalyst::BuildGraph::index_ private
Definition at line 78 of file graph.hpp.
Referenced by get_or_create_node(), and catalyst::reserve().
nodes_
std::vector<Node> catalyst::BuildGraph::nodes_ private
Definition at line 76 of file graph.hpp.
Referenced by add_step(), get_or_create_node(), nodes(), catalyst::reserve(), and topo_sort().
resources_
std::vector<std::shared_ptr<void> > catalyst::BuildGraph::resources_ private
Definition at line 79 of file graph.hpp.
Referenced by add_resource().
steps_
std::vector<BuildStep> catalyst::BuildGraph::steps_ private
Definition at line 77 of file graph.hpp.
Referenced by add_step(), and steps().
The documentation for this class was generated from the following files:
include/cbe/graph.hpp
src/graph.cpp