Catalyst Build Executor: catalyst::StatCache Class Reference
catalyst::StatCache Class Reference
Thread-safe cache for file status information (modification times).
#include <executor.hpp>
Classes
struct Entry
Public Member Functions
std::pair< std::filesystem::file_time_type, std::error_code > get_or_update (const std::filesystem::path &p)
Retrieves the last write time for a path, caching the result.
bool changed_since (const std::filesystem::path &input, std::filesystem::file_time_type output_time)
Checks if an input file has changed since a given output timestamp.
Private Attributes
std::vector< Entry > cache
std::shared_mutex cache_mtx
Detailed Description
Thread-safe cache for file status information (modification times).
This cache prevents redundant filesystem calls when checking multiple dependencies for the same file across different threads.
Definition at line 19 of file executor.hpp.
Member Function Documentation
changed_since()
bool StatCache::changed_since (const std::filesystem::path & input, std::filesystem::file_time_type output_time)
Checks if an input file has changed since a given output timestamp.
Parameters
input The input file path.
output_time The timestamp of the output file.
Returns
True if input is newer or stat failed, false otherwise.
Definition at line 35 of file executor_stat_cache.cpp.
References get_or_update().
Referenced by catalyst::Executor::needs_rebuild().
get_or_update()
auto StatCache::get_or_update (const std::filesystem::path & p)
Retrieves the last write time for a path, caching the result.
Parameters
p The file path to check.
Returns
A pair containing the last write time and any error code.
Definition at line 13 of file executor_stat_cache.cpp.
References cache, cache_mtx, and catalyst::StatCache::Entry::path.
Referenced by changed_since().
Member Data Documentation
cache
std::vector<Entry> catalyst::StatCache::cache private
Definition at line 29 of file executor.hpp.
Referenced by get_or_update().
cache_mtx
std::shared_mutex catalyst::StatCache::cache_mtx private
Definition at line 30 of file executor.hpp.
Referenced by get_or_update().
The documentation for this class was generated from the following files:
include/cbe/executor.hpp
src/executor_stat_cache.cpp