Catalyst Build Executor: catalyst::Executor Class Reference
catalyst::Executor Class Reference
Orchestrates the execution of the build graph.
#include <executor.hpp>
Public Member Functions
Executor (CBEBuilder &&builder, ExecutorConfig config={})
Result< void > execute ()
Executes the build.
Result< void > clean ()
Removes all output files generated by the build steps.
Result< void > emit_compdb ()
Generates a compile_commands.json file for tooling integration.
Result< void > emit_graph ()
Prints a Graphviz DOT representation of the build graph to stdout.
Private Member Functions
bool needs_rebuild (const BuildStep &step, StatCache &stat_cache)
Private Attributes
CBEBuilder builder
ExecutorConfig config
std::unique_ptr< WorkEstimate > estimator
std::vector< std::jthread > pool
Detailed Description
Orchestrates the execution of the build graph.
This class handles dependency analysis, parallel execution of build steps, and supporting operations like cleaning or generating a compilation database.
Definition at line 65 of file executor.hpp.
Constructor & Destructor Documentation
Executor()
catalyst::Executor::Executor (CBEBuilder && builder, ExecutorConfig config = {})
Definition at line 53 of file executor.cpp.
References config, catalyst::ExecutorConfig::estimates_file, and estimator.
Member Function Documentation
clean()
Result< void > catalyst::Executor::clean ()
Removes all output files generated by the build steps.
Returns
Success or error.
Definition at line 57 of file executor.cpp.
References builder, catalyst::CBEBuilder::emit_graph(), and catalyst::BuildGraph::steps().
emit_compdb()
Result< void > catalyst::Executor::emit_compdb ()
Generates a compile_commands.json file for tooling integration.
Returns
Success or error.
Definition at line 145 of file executor.cpp.
References builder, catalyst::CBEBuilder::definitions(), catalyst::CBEBuilder::emit_graph(), catalyst::BuildGraph::nodes(), catalyst::BuildGraph::steps(), and catalyst::BuildGraph::topo_sort().
Referenced by main().
emit_graph()
Result< void > catalyst::Executor::emit_graph ()
Prints a Graphviz DOT representation of the build graph to stdout.
Returns
Success or error.
Definition at line 114 of file executor.cpp.
References builder, catalyst::CBEBuilder::emit_graph(), needs_rebuild(), catalyst::BuildGraph::nodes(), and catalyst::BuildGraph::steps().
execute()
Result< void > catalyst::Executor::execute ()
Executes the build.
Performs a parallel walk of the build graph, executing steps whose dependencies are ready and which need rebuilding.
Returns
Success or error.
Definition at line 235 of file executor.cpp.
References catalyst::ExecutorConfig::build_file, builder, config, catalyst::CBEBuilder::definitions(), catalyst::ExecutorConfig::dry_run, catalyst::CBEBuilder::emit_graph(), estimator, catalyst::is_newer(), catalyst::ExecutorConfig::jobs, needs_rebuild(), catalyst::BuildGraph::nodes(), pool, catalyst::process_exec(), and catalyst::BuildGraph::steps().
needs_rebuild()
bool catalyst::Executor::needs_rebuild (const BuildStep & step, StatCache & stat_cache) inline private
Definition at line 81 of file executor.cpp.
References catalyst::ExecutorConfig::build_file, catalyst::StatCache::changed_since(), config, catalyst::BuildStep::depfile_inputs, catalyst::BuildStep::opaque_inputs, catalyst::BuildStep::output, and catalyst::BuildStep::parsed_inputs.
Referenced by emit_graph(), and execute().
Member Data Documentation
builder
CBEBuilder catalyst::Executor::builder private
Definition at line 100 of file executor.hpp.
Referenced by clean(), emit_compdb(), emit_graph(), and execute().
config
ExecutorConfig catalyst::Executor::config private
Definition at line 101 of file executor.hpp.
Referenced by execute(), Executor(), and needs_rebuild().
estimator
std::unique_ptr<WorkEstimate> catalyst::Executor::estimator private
Definition at line 102 of file executor.hpp.
Referenced by execute(), and Executor().
pool
std::vector<std::jthread> catalyst::Executor::pool private
Definition at line 103 of file executor.hpp.
Referenced by execute().
The documentation for this class was generated from the following files:
include/cbe/executor.hpp
src/executor.cpp