Catalyst Build Executor: catalyst Namespace Reference
catalyst Namespace Reference
Namespaces
namespace anonymous_namespace{binary.cpp}
namespace anonymous_namespace{parser.cpp}
Classes
class BuildGraph
Represents the dependency graph of the build system.
struct BuildStep
Represents a single build step execution.
class CBEBuilder
Builder class for constructing the build graph.
class Executor
Orchestrates the execution of the build graph.
struct ExecutorConfig
class MappedFile
cross-platform read-only memory mapped file wrapper.
class StatCache
Thread-safe cache for file status information (modification times).
class WorkEstimate
Typedefs
using Definitions = std::unordered_map< std::string_view, std::string_view >
Global definitions/variables for the build (e.g., compiler flags, tool paths).
template<typename T >
using Result = std::expected< T, std::string >
Functions
Result< void > parse_bin (CBEBuilder &builder)
Parses the binary cache format (.catalyst.bin).
Result< void > emit_bin (CBEBuilder &builder)
Serializes the current build graph to the binary cache format.
Result< void > parse (CBEBuilder &builder, const std::filesystem::path &path)
Parses a build manifest file.
Result< int > process_exec (std::vector< std::string > &&args, std::optional< std::string > working_dir=std::nullopt, std::optional< std::unordered_map< std::string, std::string > > env=std::nullopt)
Executes a subprocess.
if (header->strings_size > content.size() - sizeof(BinHeader))
for (uint64_t i=0;i< header->num_definitions;++i)
builder graph_ nodes_ reserve (header->num_nodes)
builder add_resource (file)
bool file_changed_since (const std::filesystem::path &input_file, const auto &out_mod_time)
bool is_newer (const std::filesystem::path &new_file, const std::filesystem::path &old_file)
void parse_depfile (BuildGraph &graph, const std::filesystem::path &path, auto callback)
Parses a Makefile-style dependency file (.d).
Variables
const char * ptr = content.data() + sizeof(BinHeader)
const char * strings_base = content.data() + content.size() - header->strings_size
auto get_sv = [&](StringRef ref) -> std::string_view { return {strings_base + ref.offset, ref.len}; }
return {}
Typedef Documentation
Definitions
using catalyst::Definitions = typedef std::unordered_map<std::string_view, std::string_view>
Global definitions/variables for the build (e.g., compiler flags, tool paths).
Definition at line 41 of file domain.hpp.
Result
template<typename T > using catalyst::Result = typedef std::expected<T, std::string>
Definition at line 6 of file utility.hpp.
Function Documentation
add_resource()
builder catalyst::add_resource (file)
emit_bin()
Result< void > catalyst::emit_bin (CBEBuilder & builder)
Serializes the current build graph to the binary cache format.
Parameters
builder The builder containing the graph to serialize.
Returns
Success or error.
file_changed_since()
bool catalyst::file_changed_since (const std::filesystem::path & input_file, const auto & out_mod_time)
Definition at line 34 of file executor.cpp.
for()
catalyst::for (uint64_t i = 0; i < header->num_definitions; ++i)
Definition at line 96 of file binary.cpp.
References catalyst::CBEBuilder::add_definition(), get_sv, and ptr.
if()
catalyst::if (header-> strings_size, content. size) - sizeof(BinHeader)
Definition at line 86 of file binary.cpp.
is_newer()
bool catalyst::is_newer (const std::filesystem::path & new_file, const std::filesystem::path & old_file)
Definition at line 42 of file executor.cpp.
Referenced by catalyst::Executor::execute().
parse()
Result< void > catalyst::parse (CBEBuilder & builder, const std::filesystem::path & path)
Parses a build manifest file.
Detects if a binary cache exists and is up-to-date; if so, loads that. Otherwise, parses the text-based manifest format.
Parameters
builder The builder to populate with parsed steps and definitions.
path The path to the manifest file (typically "catalyst.build").
Returns
Success or error.
Definition at line 56 of file parser.cpp.
Referenced by main().
parse_bin()
Result< void > catalyst::parse_bin (CBEBuilder & builder)
Parses the binary cache format (.catalyst.bin).
This is a fast-path loading mechanism that bypasses text parsing.
Parameters
builder The builder to populate.
Returns
Success or error.
Definition at line 62 of file binary.cpp.
parse_depfile()
void catalyst::parse_depfile (BuildGraph & graph, const std::filesystem::path & path, auto callback)
Parses a Makefile-style dependency file (.d).
This parser handles line continuations () and escaped spaces. It invokes the callback for each dependency found.
Parameters
graph The build graph (used to keep the memory mapped file alive).
path The path to the dependency file.
callback A callable that accepts a std::string_view for each dependency.
Definition at line 40 of file graph.cpp.
References catalyst::BuildGraph::add_resource(), and ptr.
Referenced by catalyst::BuildGraph::add_step().
process_exec()
Result< int > catalyst::process_exec (std::vector< std::string > && args, std::optional< std::string > working_dir = std::nullopt, std::optional< std::unordered_map< std::string, std::string > > env = std::nullopt)
Executes a subprocess.
Parameters
args The command line arguments (first argument is the executable).
working_dir Optional working directory for the subprocess.
env Optional environment variables to extend/override the parent environment.
Returns
The exit code of the process on success, or -1 on error.
Definition at line 15 of file process_exec.cpp.
Referenced by catalyst::Executor::execute().
reserve()
builder graph_ steps_ catalyst::reserve (header-> num_nodes)
References get_sv, catalyst::CBEBuilder::graph_, catalyst::BuildGraph::index_, catalyst::BuildGraph::nodes_, and ptr.
Variable Documentation
get_sv
auto catalyst::get_sv = [&](StringRef ref) -> std::string_view { return {strings_base + ref.offset, ref.len}; }
Definition at line 93 of file binary.cpp.
Referenced by for(), and reserve().
ptr
const char* catalyst::ptr = content.data() + sizeof(BinHeader)
Definition at line 90 of file binary.cpp.
Referenced by for(), catalyst::WorkEstimate::get_work_estimate(), parse_depfile(), and reserve().
return
catalyst::return {}
Definition at line 174 of file binary.cpp.
strings_base
const char* catalyst::strings_base = content.data() + content.size() - header->strings_size
Definition at line 91 of file binary.cpp.