Catalyst Build Executor: catalyst::anonymous_namespace{parser.cpp} Namespace Reference
catalyst::anonymous_namespace{parser.cpp} Namespace Reference
Functions
Result< void > parse_def (const std::string_view line, CBEBuilder &builder)
Result< void > parse_step (const std::string_view line, CBEBuilder &builder)
Function Documentation
parse_def()
Result< void > catalyst::anonymous_namespace{parser.cpp}::parse_def (const std::string_view line, CBEBuilder & builder)
Definition at line 15 of file parser.cpp.
References catalyst::CBEBuilder::add_definition(), and parse_def().
Referenced by parse_def().
parse_step()
Result< void > catalyst::anonymous_namespace{parser.cpp}::parse_step (const std::string_view line, CBEBuilder & builder)
Definition at line 33 of file parser.cpp.
References catalyst::CBEBuilder::add_step(), and parse_step().
Referenced by parse_step().